global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Spring Boot Actuator metrics
  - job_name: "spring-boot"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["springboot:8085"]
        labels:
          application: 'booker'
          service: 'api'

  # MySQL Exporter metrics  
  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-exporter:9104"]
        labels:
          database: 'mysql'
          instance: 'booker'

  # K6 metrics are sent directly to InfluxDB, not Prometheus
  # K6 dashboard uses InfluxDB as datasource
