import { Event, EventStats } from './types';

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Design Thinking Workshop',
    description: 'Learn the fundamentals of design thinking and its application in problem-solving.',
    imageUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&h=400&fit=crop',
    startDate: '2025-06-20',
    endDate: '2025-06-20',
    startTime: '09:00',
    endTime: '16:00',
    location: 'Training Room 3A',
    eventType: 'Workshop',
    maxParticipants: 30,
    currentParticipants: 15,
    requirements: ['Laptop required', 'Materials Provided'],
    status: 'active',
  },
  {
    id: '2',
    title: 'Summer Team Building',
    description: 'Join us for an outdoor team building event to strengthen collaboration and have fun!',
    imageUrl: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&h=400&fit=crop',
    startDate: '2025-06-25',
    endDate: '2025-06-25',
    startTime: '10:00',
    endTime: '17:00',
    location: 'Central Park',
    eventType: 'Team Building',
    maxParticipants: 50,
    currentParticipants: 42,
    requirements: ['Comfortable clothing', 'Sun protection recommended'],
    status: 'active',
  },
  {
    id: '3',
    title: 'React Advanced Patterns',
    description: 'Deep dive into advanced React patterns including hooks, context, and performance optimization.',
    imageUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&h=400&fit=crop',
    startDate: '2025-06-28',
    endDate: '2025-06-28',
    startTime: '14:00',
    endTime: '18:00',
    location: 'Conference Room B',
    eventType: 'Tech Talk',
    maxParticipants: 25,
    currentParticipants: 18,
    requirements: ['Laptop required', 'Basic React knowledge'],
    status: 'active',
  },
  {
    id: '4',
    title: 'AI & Machine Learning Basics',
    description: 'Introduction to artificial intelligence and machine learning concepts for developers.',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=400&fit=crop',
    startDate: '2025-07-05',
    endDate: '2025-07-05',
    startTime: '13:00',
    endTime: '17:00',
    location: 'Innovation Hub',
    eventType: 'Tech Talk',
    maxParticipants: 40,
    currentParticipants: 32,
    requirements: ['Programming experience', 'Materials Provided'],
    status: 'active',
  },
];

export const mockStats: EventStats = {
  activeEvents: 12,
  activeEventsThisWeek: 4,
  totalRegistrations: 248,
  totalEventsAllTime: 45,
};
