{
 "title": "JVM metrics",
 "description": "Dashboard for JVM metrics within Kubernetes, where Prometheus installed using community helm chart",
 "tags": [
  "JVM",
  "Kubernetes",
  "Helm",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "pod", "label": "Pod", "query": { "query": "label_values(jvm_info,pod)" } }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{pod=\"$pod\"}*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "label_join(jvm_info{pod=\"$pod\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{pod=~\"$pod\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Memory area",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{pod=\"$pod\"}",
     "legendFormat": "Used {{ area }}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{ pod=\"$pod\"}",
     "legendFormat": "loaded"
    },
    {
     "expr": "jvm_classes_unloaded_total{ pod=\"$pod\"}",
     "legendFormat": "unloaded"
    }
   ]
  },
  {
   "title": "Survivor Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "repeat": "mempool",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Survivor Space\", pod=\"$pod\"}",
     "legendFormat": "Max {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Survivor Space\", pod=\"$pod\"}",
     "legendFormat": "Used {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Survivor Space\", pod=\"$pod\"}",
     "legendFormat": "Committed {{ pool }}"
    }
   ]
  },
  {
   "title": "Eden Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Eden Space\", pod=\"$pod\"}",
     "legendFormat": "Max {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Eden Space\", pod=\"$pod\"}",
     "legendFormat": "Used {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Eden Space\", pod=\"$pod\"}",
     "legendFormat": "Committed {{ pool }}"
    }
   ]
  },
  {
   "title": "Old Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Tenured Gen\", pod=\"$pod\"}",
     "legendFormat": "Max {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Tenured Gen\", pod=\"$pod\"}",
     "legendFormat": "Used {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Tenured Gen\", pod=\"$pod\"}",
     "legendFormat": "Committed {{ pool }}"
    }
   ]
  },
  { "title": "Threads ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Threads State",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{pod=\"$pod\",state=\"RUNNABLE\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "jvm_threads_state{pod=\"$pod\",state=\"BLOCKED\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "jvm_threads_state{pod=\"$pod\",state=\"NEW\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "jvm_threads_state{pod=\"$pod\",state=\"TERMINATED\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "jvm_threads_state{pod=\"$pod\",state=\"TIMED_WAITING\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "jvm_threads_state{pod=\"$pod\",state=\"WAITING\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{pod=\"$pod\"}",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "jvm_threads_daemon{pod=\"$pod\"}",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{pod=\"$pod\"}",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  }
 ]
}