server:
  port: 8084

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_INTERNAL_URL}/realms/myrealm
            authorization-uri: ${KEYCLOAK_EXTERNAL_URL}/realms/myrealm/protocol/openid-connect/auth
            token-uri: ${KEYCLOAK_INTERNAL_URL}/realms/myrealm/protocol/openid-connect/token
            user-info-uri: ${KEYCLOAK_INTERNAL_URL}/realms/myrealm/protocol/openid-connect/userinfo
            jwk-set-uri: ${KEYCLOAK_INTERNAL_URL}/realms/myrealm/protocol/openid-connect/certs
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: springboot-client
            client-secret: springboot-secret
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8084/login/oauth2/code/keycloak
            scope: openid,profile,email 