server:
  port: 8084
  tomcat:
    threads:
      max: 300
      min-spare: 20
    accept-count: 200
    max-connections: 10000
    connection-timeout: 60000
    keep-alive-timeout: 60000
    max-keep-alive-requests: 1000

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/booker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&connectTimeout=30000&socketTimeout=60000&autoReconnect=true&tcpKeepAlive=true&maxReconnects=3&initialTimeout=1
    username: booker
    password: booker123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 200
      minimum-idle: 20
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true

keycloak:
  auth-server-url: http://keycloak:8083
  realm: myrealm
  client-id: springboot-client

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.bookerapp.core.presentation.controller

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.bookerapp.core: DEBUG
    com.bookerapp.core.infrastructure.config.JwtConfig: DEBUG
    com.bookerapp.core.presentation.interceptor.JwtAuthInterceptor: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.servlet.mvc: DEBUG
    org.springframework.web.servlet.handler: DEBUG
    org.springframework.web.bind: DEBUG
    org.springframework.validation: DEBUG
    com.fasterxml.jackson: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.dao: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: prometheus

google:
  calendar:
    credentials-file-path: ${GOOGLE_CALENDAR_CREDENTIALS_PATH}
    application-name: Booker
    calendar-id: ${GOOGLE_CALENDAR_ID}
