server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: booker
    password: booker123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true
  
keycloak:
  auth-server-url: http://keycloak:8083
  realm: myrealm
  client-id: springboot-client

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.bookerapp.core.presentation.controller

logging:
  level:
    root: INFO    
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.bookerapp.core: DEBUG
    com.bookerapp.core.infrastructure.config.JwtConfig: DEBUG
    com.bookerapp.core.presentation.interceptor.JwtAuthInterceptor: DEBUG 
